# Generated by Django 4.1.5 on 2023-01-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик объявления"),
                            ("published", "Опубликованное объявление"),
                            ("closed", "Снято с публикации"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик категории"),
                            ("published", "Размещенная категория"),
                            ("closed", "Закрытая категория"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("name", models.SlugField()),
            ],
        ),
    ]
