# Generated by Django 4.1.5 on 2023-01-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ads",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
