# Generated by Django 4.1.5 on 2023-01-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ads_is_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ads",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="categories",
            name="slug",
        ),
    ]
