# Generated by Django 4.1.5 on 2023-01-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_remove_ads_slug_remove_categories_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
