# Generated by Django 4.1.5 on 2023-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0005_ads_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
