# Generated by Django 4.1.5 on 2023-01-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0006_alter_ads_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="is_published",
            field=models.CharField(max_length=100),
        ),
    ]
