# Generated by Django 4.0.1 on 2023-02-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
