# Generated by Django 4.0.1 on 2023-02-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_location_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='author',
        ),
        migrations.AddField(
            model_name='ads',
            name='user',
            field=models.ManyToManyField(to='ads.Users'),
        ),
    ]
