# Generated by Django 4.0.1 on 2023-02-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_remove_ads_author_ads_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='user_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='user',
            field=models.ManyToManyField(null=True, to='ads.Users'),
        ),
    ]
