# Generated by Django 4.0.1 on 2023-02-05 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0014_ads_user_id_alter_ads_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='user',
        ),
        migrations.AlterField(
            model_name='ads',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.users'),
        ),
    ]
