# Generated by Django 4.0.1 on 2023-02-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_ads_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
