# Generated by Django 4.0.1 on 2023-02-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0017_alter_ads_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='address',
        ),
    ]
