# Generated by Django 4.0.1 on 2023-02-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0019_alter_location_lat_alter_location_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.ManyToManyField(null=True, to='ads.Location'),
        ),
    ]
